language: java
jdk:
  - openjdk10
  - opendjk11

os: linux
dist: xenial

branches:
  only:
    - 1.x
    - 2.x
    - /^\d+\.\d+\.\d+(-\S*)?$/

#before_install:
#  - rm "${JAVA_HOME}/lib/security/cacerts"
#  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install: echo skip

git:
  depth: 200

jobs:
  include:
    - stage: build
      name: Core
      script: ./gradlew --stacktrace spek-dsl:build spek-runtime:build
    - name: JUnit 5 Runner
      script: ./gradlew --stacktrace spek-runner:junit5:build
      os: linux
    - name: IntelliJ IDEA Plugin
      script:
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ182
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ183
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ191
      os: linux
    - name: Android Studio Plugin
      script:
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:buildPlugin -Pas.version=AS33
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:buildPlugin -Pas.version=AS34
      os: linux
#    - stage: build-jdk11
#      script:
#        - ./gradlew --stacktrace clean build
#        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ182
#        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ183
#        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:buildPlugin -Pij.version=IJ191
#        - ./gradlew --stacktrace spek-ide-plugin:android-studio:buildPlugin -Pas.version=AS33
#        - ./gradlew --stacktrace spek-ide-plugin:android-studio:buildPlugin -Pas.version=AS34
#      jdk: openjdk11
    - stage: release
      script:
        - ./gradlew --stacktrace bintrayUpload
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ182
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ183
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ191
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:clean spek-ide-plugin:android-studio:publishPlugin -Pas.version=AS33
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:clean spek-ide-plugin:android-studio:publishPlugin -Pas.version=AS34
        - curl -X POST -d '' $NETLIFY_DEPLOY_URL
    - stage: release-dev
      script:
        - ./gradlew --stacktrace bintrayUpload
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ182
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ183
        - ./gradlew --stacktrace spek-ide-plugin:intellij-idea:clean spek-ide-plugin:intellij-idea:publishPlugin -Pij.version=IJ191
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:clean spek-ide-plugin:android-studio:publishPlugin -Pas.version=AS33
        - ./gradlew --stacktrace spek-ide-plugin:android-studio:clean spek-ide-plugin:android-studio:publishPlugin -Pas.version=AS34

stages:
  - build
#  - build-jdk11
  - name: release
    if: tag IS present AND repo = "spekframework/spek"
  - name: release-dev
    if: tag IS NOT present AND type != pull_request AND repo = "spekframework/spek"

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle

notifications:
  email:
    recipients:
      - artem.zinnatullin@gmail.com
      - raniejaderamiso@gmail.com
    on_success: never
    on_failure: always
